version: "3.8"

services:
  julong-recruitment:
    container_name: julong-recruitment
    build:
      context: .
      dockerfile: Dockerfile
      args:
        NEXT_PUBLIC_API_BASE_URL: https://hris.julongindonesia.com:5503
        NEXT_PUBLIC_API_MPP: https://hris.julongindonesia.com:5502
        NEXT_PUBLIC_API_PORTAL: https://hris.julongindonesia.com:5501
        NEXT_PUBLIC_API_RECRUITMENT: https://hris.julongindonesia.com:5503
        NEXT_PUBLIC_MAIN_URL: hris.julongindonesia.com
        NEXT_PUBLIC_BASE_URL: https://hris.julongindonesia.com:3002
        NEXT_PUBLIC_MODE: production
        NEXT_PUBLIC_NAME: recruitment
        NODE_ENV: production
    ports:
      - "3002:3000"
    restart: unless-stopped
    networks:
      - web

networks:
  web:
    driver: bridge
